### ISSUE TITLE
Ignore packages in pacupg

### ISSUE THREAD

**Issue by ardichoke** [crossroads1112/bin#3]
Would it be possible to add an --ignore option in pacupg, which functions the same as --ignore in pacman? Reason being, I've had some issues recently with specific upgrades breaking my system. After a rollback, I'd like to do the upgrades that DON'T break everything, and the easiest way to do that would be to simply --ignore packagename.

Alternatively, could the ability to specify which packages to upgrade be added?  For example, if I wanted to upgrade just gnupg, I could just run pacupg gnupg.

**Comment by cmlsharp** [comment]
In regards to your first solution, is there a particular reason putting the packages in `IgnorePkgs` in `/etc/pacman.conf` does not work for you?

**Comment by cmlsharp** [comment]
Regardless, I added a `--ignore` option. See 6ff08c0

**Comment by ardichoke** [comment]
Thanks, there wasn't a problem with adding it to the config, per se... it's more of a conceptual distinction. Modifying the configuration file is meant for more permanent changes and adding it there one runs the risk of forgetting to remove it and then being confused in the future about why certain packages aren't being updated. Having the command line switch is useful for one-off ignores, when there is a singular bum update.
