### ISSUE TITLE
Failed dependencies with ignored packages

### ISSUE THREAD

**Issue by ardichoke** [crossroads1112/bin#4]
When there are packages that are marked as ignored in pacman.conf, if the ignored package is a dependency for another upgrade, it causes the upgrade process to fail. On the first pass, it appropriately stops and asks if you want to skip the package with the unsatisfied dependency:

```
:: The following package cannot be upgraded due to unresolvable dependencies:
      virtualbox-host-modules

:: Do you want to skip the above package for this upgrade? [y/N] 
```

If you enter 'y' at this point, it will continue and not download the package(s) with unresolvable dependencies, as expected. However, when it gets to the installation step, this question comes up again and you are not given the option to skip the package, it immediately chooses the default and the upgrade fails.

```
:: The following package cannot be upgraded due to unresolvable dependencies:
      virtualbox-host-modules

:: Do you want to skip the above package for this upgrade? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: virtualbox-host-modules: requires linux>=4.2
! WARNING: Aborting from pre/post snapshot block Do you want to remove pre snapshot 3071? [Y/n]:
```

It seems like the behavior should be consistent between the two phases. Either a failed dependency should cause an immediate failure up front, or you should be able to skip the package with the failed dependency and install the rest of the upgrades.

**Comment by cmlsharp** [comment]
One of the problems with this being a bash script is that I rely on options available to me through pacman and pacupg. I can't think of a solution to this problem other than not having it call `--noconfirm` for the upgrade portion
