### ISSUE TITLE
Cleanup old upgrade snapshots

### ISSUE THREAD

**Issue by Psykar** [crossroads1112/bin#5]
Love it.
I would like an option however, to run to delete snapshots older than x days, or to keep only x number of hem. I don't really need upgrade snapshots older than a month, as I use snapper timeline ones anyway, it's more for rolling back from an immediate issue caused in the last few days.

Something that's been considered at all?

**Comment by cmlsharp** [comment]
That is out of the scope of this script. This can be achieved by editing your snapper config.

**Comment by Psykar** [comment]
Apologies, I looked closer at snapper config and found 'NUMBER_CLEANUP' (which I don't recall previously - I was only aware of the timeline cleanups)

Thanks.
