### ISSUE TITLE
--aur option updates not persistent

### ISSUE THREAD

**Issue by sdothum** [crossroads1112/bin#9]
By that I mean, pacupg --aur installs the aur packages after the system  upgrades but upon rerunning pacupg --aur, the same packages are flagged as out of date and needing reinstalling.

Very puzzling. A snapshot issue?

To get around this, I wrote a wrapper to perform pacaur aur updates before running pacupg (without the --aur flag).

**Comment by cmlsharp** [comment]
Would you mind posting command line output that demonstrates what you are seeing?

**Comment by sdothum** [comment]
Need to wait for an aur package update.. in the meantime, what transpires is that pacupg performs system updates followed by any aur updates. However, on a subsequent pacupg --aur, the same aur packages are listed for updating again. Hence, I run pacaur --aur BEFORE running pacupg (minus --aur option). Don't know why running pacaur --aur before pacupg works since pacupg --aur runs pacaur --aur. Puzzling.

**Comment by sdothum** [comment]
Well, finally came across some aur updates running pacupg --aur, and the reported problem no longer occurs. Not sure what dependency got cleared up, but this problem (which persisted for several weeks) has resolved itself and pacupg is running as it used to!
